version: "3"
services:

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: super
      MYSQL_DATABASE: kata-api
    volumes:
      - ./initSQL:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080